module.exports = {
  SHOW_DETAIL: 'SHOW_DETAIL',
  HIDE_DETAIL: 'HIDE_DETAIL',
  SHOW_OVERVIEW: 'SHOW_OVERVIEW',
  HIDE_OVERVIEW: 'HIDE_OVERVIEW',
  SHOW_ALL: 'SHOW_ALL',
  SEARCH: 'SEARCH',
  POPULATE: 'POPULATE',
  GET_BINDERS: 'GET_BINDERS',
  GET_BINDERS_FAILED: 'GET_BINDERS_FAILED',
  GET_BINDERS_SUCCEEDED: 'GET_BINDERS_SUCCEEDED',
  BUILD_STATE_SUCCEEDED: 'BUILD_STATE_SUCCEEDED',
  BUILD_STATE_FAILED: 'BUILD_STATE_FAILED'
}
